from pathlib import Path
from datetime import datetime


class ReportGenerator:

    @staticmethod
    def generate(
        result,
        strategy_name,
        symbol,
        interval,
        output_file="reports/backtest_report.html",
    ):

        portfolio = result.portfolio

        Path(output_file).parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        trades_html = portfolio.trade_dataframe().to_html(
            index=False,
            classes="trade-table",
            border=0,
        )

        html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8">

<title>Falcon Backtest Report</title>

<style>

body {{

    font-family: Arial, sans-serif;
    background:#f5f5f5;
    margin:40px;

}}

.container {{

    background:white;

    padding:40px;

    border-radius:10px;

}}

table {{

    width:100%;

    border-collapse:collapse;

}}

th,td {{

    border:1px solid #ddd;

    padding:8px;

}}

th {{

    background:#1f2937;

    color:white;

}}

.metric {{

    display:inline-block;

    width:250px;

    margin-bottom:12px;

}}

iframe {{

    width:100%;

    height:650px;

    border:none;

}}

</style>

</head>

<body>

<div class="container">

<h1>Project Falcon</h1>

<h2>Backtest Report</h2>

<p><b>Generated:</b> {datetime.now()}</p>

<hr>

<h2>Configuration</h2>

<p><b>Strategy:</b> {strategy_name}</p>

<p><b>Symbol:</b> {symbol}</p>

<p><b>Interval:</b> {interval}</p>

<hr>

<h2>Portfolio Summary</h2>

<div class="metric"><b>Initial Capital:</b> ₹{portfolio.initial_capital:,.2f}</div>

<div class="metric"><b>Final Capital:</b> ₹{portfolio.capital:,.2f}</div>

<div class="metric"><b>Total PnL:</b> ₹{portfolio.total_pnl:,.2f}</div>

<div class="metric"><b>Return:</b> {portfolio.total_return_pct:.2f}%</div>

<div class="metric"><b>Total Trades:</b> {portfolio.total_trades}</div>

<div class="metric"><b>Winning Trades:</b> {portfolio.winning_trades}</div>

<div class="metric"><b>Losing Trades:</b> {portfolio.losing_trades}</div>

<div class="metric"><b>Win Rate:</b> {portfolio.win_rate:.2f}%</div>

<div class="metric"><b>Profit Factor:</b> {portfolio.profit_factor:.2f}</div>

<hr>

<h2>Performance Metrics</h2>

<pre>{result.performance}</pre>

<hr>

<h2>Drawdown</h2>

<pre>{result.drawdown}</pre>

<hr>

<h2>Equity Curve</h2>

<iframe src="equity_curve.html"></iframe>

<hr>

<h2>Drawdown Curve</h2>

<iframe src="drawdown_curve.html"></iframe>

<hr>

<h2>Trade Chart</h2>

<iframe src="trade_chart.html"></iframe>

<hr>

<h2>Trade History</h2>

{trades_html}

<hr>

<p align="center">

Generated by <b>Project Falcon</b>

</p>

</div>

</body>

</html>
"""

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(html)

        print(f"Report saved to {output_file}")