"""Equity overlay chart for comparison results."""

from __future__ import annotations

import plotly.graph_objects as go
import streamlit as st

from app.comparison.comparison_result import ComparisonResult
from app.visualization.themes import dark


def render(results: list[ComparisonResult]) -> None:
    """Render the equity curves generated by completed backtests."""
    figure = go.Figure()
    for item in results:
        equity = item.result.portfolio.equity_curve
        figure.add_trace(
            go.Scatter(
                x=list(range(len(equity))), y=equity, mode="lines", name=item.strategy_name
            )
        )
    figure.update_layout(
        title="Strategy Equity Curves", xaxis_title="Closed Trades",
        yaxis_title="Portfolio Value (₹)", template="plotly_dark",
        paper_bgcolor=dark.PAPER, plot_bgcolor=dark.BACKGROUND,
        height=450, hovermode="x unified",
    )
    st.plotly_chart(figure, use_container_width=True)
